DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM requests;
DELETE FROM users;
ALTER SEQUENCE postgres.public.items_id_seq
RESTART WITH 1;
ALTER SEQUENCE postgres.public.requests_id_seq
    RESTART WITH 1;
ALTER SEQUENCE postgres.public.users_id_seq
    RESTART WITH 1;
ALTER SEQUENCE postgres.public.bookings_id_seq
    RESTART WITH 1;
ALTER SEQUENCE postgres.public.comments_id_seq
    RESTART WITH 1;